# authentication credentials
credentials:
  usernames:
    kalim:
      email: kalim@gmail.com
      name: Kalim Amzad
      password: $2b$12$Vya.5Gw0ur0pDxsjt22/suzsNMS/xXYti30GXZZFQ62nUWwmcLJFm

cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - kalim@growwithdata.net




db:
  host: "localhost"
  user: "root"
  passwd: "123456"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"


email_sender:
  email: "kalim.resource@gmail.com"
  pass: "6554321"